(() => {
  const columns = [["original", "原图"], ["lora", "4K-效果1（加 LoRA）"], ["noLora", "4K-效果2（不加 LoRA）"], ["aiBeauty", "2K-效果"]];
  const scenes = Array.from({length:25}, (_, i) => {
    const n = i + 1, two = String(n).padStart(2, "0"), f = (d, x) => `./assets/${d}/${x}`;
    return { id: `scene-${two}`, number: n,
      images: { original: f("original", `4k-${n}.jpg`), lora: f("lora", `${two}.jpg`), noLora: f("no-lora", `${two}.jpg`), aiBeauty: f("ai-beauty", `${two}.jpg`) },
      thumbs: { original: f("thumbs/original", `4k-${n}.jpg`), lora: f("thumbs/lora", `${two}.jpg`), noLora: f("thumbs/no-lora", `${two}.jpg`), aiBeauty: f("thumbs/ai-beauty", `${two}.jpg`) }
    };
  });
  const app=document.querySelector("#app"); let query="", singleState=null, pan=null;
  const esc=v=>String(v).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
  function render(){const rows=scenes.filter(s=>!query||String(s.number).includes(query)); app.innerHTML=`<div class="app"><header class="topbar"><div class="brand"><div><h1>4K增强效果测试结果</h1><p>4K 离线渲染图对比 · 加 LoRA 与不加 LoRA 版本</p></div></div><div class="summary"><strong>${rows.length}</strong> / ${scenes.length} 组</div></header><main class="shell"><div class="filterbar"><div class="filter-group"><span class="filter-label">测试结果</span><span class="hint">点击图片查看大图，支持滚轮缩放与拖拽</span></div><input class="search" value="${esc(query)}" placeholder="搜索序号" aria-label="搜索序号" /></div><section class="showcase"><div class="table-grid"><div class="th th-index">序号</div>${columns.map(([,l],i)=>`<div class="th ${i>0&&i<3?"th-result":i===3?"th-ai":""}">${esc(l)}</div>`).join("")}${rows.map(row).join("")}</div></section></main>${modalMarkup()}</div>`; bind();}
  function row(s){return `<div class="td index-cell"><span>${String(s.number).padStart(2,"0")}</span></div>${columns.map(([k,l])=>{const c=k?`<div class="thumb-actions"><button data-compare="${s.id}" data-left="original" data-right="${k}" data-left-label="原图" data-right-label="${esc(l)}">↔ 原图对比</button>${k!=="aiBeauty"?`<button data-compare="${s.id}" data-left="${k}" data-right="aiBeauty" data-left-label="${esc(l)}" data-right-label="2K-效果">↔ 2K效果对比</button>`:""}</div>`:"";return `<div class="td"><div class="thumb"><img src="${s.thumbs[k]}" alt="${esc(l)} ${s.number}" loading="eager" decoding="async" data-single="${s.id}" data-key="${k}" title="点击查看大图"/>${c}</div></div>`}).join("")}`}
  function modalMarkup(){return `<div class="modal" role="dialog" aria-modal="true"><div class="modal-panel"><div class="modal-head"><strong class="modal-title"></strong><span class="zoom-hint">滚轮缩放 · 拖拽查看细节</span><button class="modal-close" aria-label="关闭">×</button></div><div class="stage-wrap"><button class="single-nav single-prev">‹</button><div class="stage"><img class="after"/><div class="before-wrap"><img class="before"/></div><div class="handle">↔</div><input type="range" min="0" max="100" value="50"/><span class="badge left"></span><span class="badge right"></span></div><button class="single-nav single-next">›</button></div></div></div>`}
  function bind(){const q=app.querySelector(".search");q.addEventListener("input",()=>{query=q.value.trim();render();app.querySelector(".search").focus()});app.querySelectorAll("[data-compare]").forEach(b=>b.addEventListener("click",()=>openCompare(b.dataset)));app.querySelectorAll("[data-single]").forEach(i=>i.addEventListener("click",()=>openSingle(i.dataset.single,i.dataset.key)));app.querySelector(".single-prev").addEventListener("click",()=>changeSingle(-1));app.querySelector(".single-next").addEventListener("click",()=>changeSingle(1));app.querySelector(".modal-close").addEventListener("click",closeModal);app.querySelector(".modal").addEventListener("click",e=>{if(e.target.classList.contains("modal"))closeModal()});const st=app.querySelector(".stage");st.addEventListener("wheel",e=>{e.preventDefault();zoom(e.deltaY<0?1.15:1/1.15)},{passive:false});st.addEventListener("pointerdown",startPan);window.addEventListener("pointermove",movePan);window.addEventListener("pointerup",()=>pan=null);st.querySelector("input").addEventListener("input",e=>st.style.setProperty("--split",`${e.target.value}%`))}
  function scene(id){return scenes.find(s=>s.id===id)} function ratio(im,st){const u=()=>{if(im.naturalHeight)st.style.setProperty("--image-ratio",im.naturalWidth/im.naturalHeight)};im.onload=u;if(im.complete)u()}
  function reset(st){st.dataset.zoom="1";st.dataset.panX="0";st.dataset.panY="0";st.style.setProperty("--zoom",1);st.style.setProperty("--pan-x","0px");st.style.setProperty("--pan-y","0px")}
  function openCompare(d){const s=scene(d.compare),m=app.querySelector(".modal"),st=m.querySelector(".stage");singleState=null;m.classList.remove("single");m.querySelector(".modal-title").textContent=`${String(s.number).padStart(2,"0")} · ${d.leftLabel} / ${d.rightLabel}`;m.querySelector(".before").src=s.images[d.left];m.querySelector(".after").src=s.images[d.right];ratio(m.querySelector(".after"),st);m.querySelector(".badge.left").textContent=d.leftLabel;m.querySelector(".badge.right").textContent=d.rightLabel;st.style.setProperty("--split","50%");m.querySelector("input").value=50;reset(st);m.classList.add("open")}
  function openSingle(id,key){singleState={id,index:Math.max(0,columns.findIndex(([k])=>k===key))};showSingle()} function showSingle(){const {id,index}=singleState,[k,l]=columns[index],s=scene(id),m=app.querySelector(".modal"),st=m.querySelector(".stage");m.classList.add("single");m.querySelector(".modal-title").textContent=`${String(s.number).padStart(2,"0")} · ${l} · ${index+1}/${columns.length}`;const im=m.querySelector(".after");im.src=s.images[k];ratio(im,st);reset(st);m.classList.add("open")}
  function zoom(f){const st=app.querySelector(".stage"),n=Math.min(5,Math.max(1,Number(st.dataset.zoom||1)*f));st.dataset.zoom=n;st.style.setProperty("--zoom",n)} function startPan(e){const st=e.currentTarget;if(e.target.matches("input"))return;if(Number(st.dataset.zoom||1)<=1)return;pan={st,x:e.clientX,y:e.clientY,px:Number(st.dataset.panX||0),py:Number(st.dataset.panY||0)}} function movePan(e){if(!pan)return;pan.st.dataset.panX=pan.px+e.clientX-pan.x;pan.st.dataset.panY=pan.py+e.clientY-pan.y;pan.st.style.setProperty("--pan-x",`${pan.st.dataset.panX}px`);pan.st.style.setProperty("--pan-y",`${pan.st.dataset.panY}px`)} function changeSingle(d){if(singleState){singleState.index=(singleState.index+d+columns.length)%columns.length;showSingle()}} function closeModal(){app.querySelector(".modal").classList.remove("open");singleState=null}
  addEventListener("keydown",e=>{if(!app.querySelector(".modal.open"))return;if(e.key==="Escape")closeModal();if(singleState&&e.key==="ArrowLeft")changeSingle(-1);if(singleState&&e.key==="ArrowRight")changeSingle(1)});render();
})();
