window.__MULI_SHOWCASE__ = {
  "rows": [
    {
      "id": 1,
      "order": 1,
      "render": "assets/render/01-render.jpg",
      "renderName": "01.jpg",
      "a": "assets/a/01-a.jpg",
      "aName": "01_效果A.jpg",
      "b": "assets/b/01-b.jpg",
      "bName": "01_效果B.jpg",
      "online": "assets/online/01-online.jpg",
      "onlineName": "01_线上效果.jpg"
    },
    {
      "id": 2,
      "order": 2,
      "render": "assets/render/02-render.jpg",
      "renderName": "02.jpg",
      "a": "assets/a/02-a.jpg",
      "aName": "02_效果A.jpg",
      "b": "assets/b/02-b.jpg",
      "bName": "02_效果B.jpg",
      "online": "assets/online/02-online.jpg",
      "onlineName": "02_线上效果.jpg"
    },
    {
      "id": 3,
      "order": 3,
      "render": "assets/render/03-render.jpg",
      "renderName": "03.jpg",
      "a": "assets/a/03-a.jpg",
      "aName": "03_效果A.jpg",
      "b": "assets/b/03-b.jpg",
      "bName": "03_效果B.jpg",
      "online": "assets/online/03-online.jpg",
      "onlineName": "03_线上效果.jpg"
    },
    {
      "id": 4,
      "order": 4,
      "render": "assets/render/04-render.jpg",
      "renderName": "04.jpg",
      "a": "assets/a/04-a.jpg",
      "aName": "04_效果A.jpg",
      "b": "assets/b/04-b.jpg",
      "bName": "04_效果B.jpg",
      "online": "assets/online/04-online.jpg",
      "onlineName": "04_线上效果.jpg"
    },
    {
      "id": 5,
      "order": 5,
      "render": "assets/render/05-render.jpg",
      "renderName": "05.jpg",
      "a": "assets/a/05-a.jpg",
      "aName": "05_效果A.jpg",
      "b": "assets/b/05-b.jpg",
      "bName": "05_效果B.jpg",
      "online": "assets/online/05-online.jpg",
      "onlineName": "05_线上效果.jpg"
    },
    {
      "id": 6,
      "order": 6,
      "render": "assets/render/06-render.jpg",
      "renderName": "06.jpg",
      "a": "assets/a/06-a.jpg",
      "aName": "06_效果A.jpg",
      "b": "assets/b/06-b.jpg",
      "bName": "06_效果B.jpg",
      "online": "assets/online/06-online.jpg",
      "onlineName": "06_线上效果.jpg"
    },
    {
      "id": 7,
      "order": 7,
      "render": "assets/render/07-render.jpg",
      "renderName": "07.jpg",
      "a": "assets/a/07-a.jpg",
      "aName": "07_效果A.jpg",
      "b": "assets/b/07-b.jpg",
      "bName": "07_效果B.jpg",
      "online": "assets/online/07-online.jpg",
      "onlineName": "07_线上效果.jpg"
    },
    {
      "id": 8,
      "order": 8,
      "render": "assets/render/08-render.jpg",
      "renderName": "08.jpg",
      "a": "assets/a/08-a.jpg",
      "aName": "08_效果A.jpg",
      "b": "assets/b/08-b.jpg",
      "bName": "08_效果B.jpg",
      "online": "assets/online/08-online.jpg",
      "onlineName": "08_线上效果.jpg"
    },
    {
      "id": 9,
      "order": 9,
      "render": "assets/render/09-render.jpg",
      "renderName": "09.jpg",
      "a": "assets/a/09-a.jpg",
      "aName": "09_效果A.jpg",
      "b": "assets/b/09-b.jpg",
      "bName": "09_效果B.jpg",
      "online": "assets/online/09-online.jpg",
      "onlineName": "09_线上效果.jpg"
    },
    {
      "id": 10,
      "order": 10,
      "render": "assets/render/10-render.jpg",
      "renderName": "10.jpg",
      "a": "assets/a/10-a.jpg",
      "aName": "10_效果A.jpg",
      "b": "assets/b/10-b.jpg",
      "bName": "10_效果B.jpg",
      "online": "assets/online/10-online.jpg",
      "onlineName": "10_线上效果.jpg"
    },
    {
      "id": 11,
      "order": 11,
      "render": "assets/render/11-render.jpg",
      "renderName": "11.jpg",
      "a": "assets/a/11-a.jpg",
      "aName": "11_效果A.jpg",
      "b": "assets/b/11-b.jpg",
      "bName": "11_效果B.jpg",
      "online": "assets/online/11-online.jpg",
      "onlineName": "11_线上效果.jpg"
    },
    {
      "id": 12,
      "order": 12,
      "render": "assets/render/12-render.jpg",
      "renderName": "12.jpg",
      "a": "assets/a/12-a.jpg",
      "aName": "12_效果A.jpg",
      "b": "assets/b/12-b.jpg",
      "bName": "12_效果B.jpg",
      "online": "assets/online/12-online.jpg",
      "onlineName": "12_线上效果.jpg"
    },
    {
      "id": 13,
      "order": 13,
      "render": "assets/render/13-render.jpg",
      "renderName": "13.jpg",
      "a": "assets/a/13-a.jpg",
      "aName": "13_效果A.jpg",
      "b": "assets/b/13-b.jpg",
      "bName": "13_效果B.jpg",
      "online": "assets/online/13-online.jpg",
      "onlineName": "13_线上效果.jpg"
    },
    {
      "id": 14,
      "order": 14,
      "render": "assets/render/14-render.jpg",
      "renderName": "14.jpg",
      "a": "assets/a/14-a.jpg",
      "aName": "14_效果A.jpg",
      "b": "assets/b/14-b.jpg",
      "bName": "14_效果B.jpg",
      "online": "assets/online/14-online.jpg",
      "onlineName": "14_线上效果.jpg"
    },
    {
      "id": 15,
      "order": 15,
      "render": "assets/render/15-render.jpg",
      "renderName": "15.jpg",
      "a": "assets/a/15-a.jpg",
      "aName": "15_效果A.jpg",
      "b": "assets/b/15-b.jpg",
      "bName": "15_效果B.jpg",
      "online": "assets/online/15-online.jpg",
      "onlineName": "15_线上效果.jpg"
    },
    {
      "id": 16,
      "order": 16,
      "render": "assets/render/16-render.jpg",
      "renderName": "16.jpg",
      "a": "assets/a/16-a.jpg",
      "aName": "16_效果A.jpg",
      "b": "assets/b/16-b.jpg",
      "bName": "16_效果B.jpg",
      "online": "assets/online/16-online.jpg",
      "onlineName": "16_线上效果.jpg"
    },
    {
      "id": 17,
      "order": 17,
      "render": "assets/render/17-render.jpg",
      "renderName": "17.jpg",
      "a": "assets/a/17-a.jpg",
      "aName": "17_效果A.jpg",
      "b": "assets/b/17-b.jpg",
      "bName": "17_效果B.jpg",
      "online": "assets/online/17-online.jpg",
      "onlineName": "17_线上效果.jpg"
    },
    {
      "id": 18,
      "order": 18,
      "render": "assets/render/18-render.jpg",
      "renderName": "18.jpg",
      "a": "assets/a/18-a.jpg",
      "aName": "18_效果A.jpg",
      "b": "assets/b/18-b.jpg",
      "bName": "18_效果B.jpg",
      "online": "assets/online/18-online.jpg",
      "onlineName": "18_线上效果.jpg"
    }
  ]
};
