window.__MULI_SHOWCASE__ = {
  "rows": [
    {
      "id": 1,
      "order": 1,
      "original": "assets-full/original/01-original.jpg",
      "originalThumb": "assets-thumb/original/01-original.jpg",
      "b": "assets-full/b/01-b.jpg",
      "bThumb": "assets-thumb/b/01-b.jpg",
      "a": "assets-full/a/01-a.jpg",
      "aThumb": "assets-thumb/a/01-a.jpg",
      "online": "assets-full/online/01-online.jpg",
      "onlineThumb": "assets-thumb/online/01-online.jpg"
    },
    {
      "id": 2,
      "order": 2,
      "original": "assets-full/original/02-original.jpg",
      "originalThumb": "assets-thumb/original/02-original.jpg",
      "b": "assets-full/b/02-b.jpg",
      "bThumb": "assets-thumb/b/02-b.jpg",
      "a": "assets-full/a/02-a.jpg",
      "aThumb": "assets-thumb/a/02-a.jpg",
      "online": "assets-full/online/02-online.jpg",
      "onlineThumb": "assets-thumb/online/02-online.jpg"
    },
    {
      "id": 3,
      "order": 3,
      "original": "assets-full/original/03-original.jpg",
      "originalThumb": "assets-thumb/original/03-original.jpg",
      "b": "assets-full/b/03-b.jpg",
      "bThumb": "assets-thumb/b/03-b.jpg",
      "a": "assets-full/a/03-a.jpg",
      "aThumb": "assets-thumb/a/03-a.jpg",
      "online": "assets-full/online/03-online.jpg",
      "onlineThumb": "assets-thumb/online/03-online.jpg"
    },
    {
      "id": 4,
      "order": 4,
      "original": "assets-full/original/04-original.jpg",
      "originalThumb": "assets-thumb/original/04-original.jpg",
      "b": "assets-full/b/04-b.jpg",
      "bThumb": "assets-thumb/b/04-b.jpg",
      "a": "assets-full/a/04-a.jpg",
      "aThumb": "assets-thumb/a/04-a.jpg",
      "online": "assets-full/online/04-online.jpg",
      "onlineThumb": "assets-thumb/online/04-online.jpg"
    },
    {
      "id": 5,
      "order": 5,
      "original": "assets-full/original/05-original.jpg",
      "originalThumb": "assets-thumb/original/05-original.jpg",
      "b": "assets-full/b/05-b.jpg",
      "bThumb": "assets-thumb/b/05-b.jpg",
      "a": "assets-full/a/05-a.jpg",
      "aThumb": "assets-thumb/a/05-a.jpg",
      "online": "assets-full/online/05-online.jpg",
      "onlineThumb": "assets-thumb/online/05-online.jpg"
    },
    {
      "id": 6,
      "order": 6,
      "original": "assets-full/original/06-original.jpg",
      "originalThumb": "assets-thumb/original/06-original.jpg",
      "b": "assets-full/b/06-b.jpg",
      "bThumb": "assets-thumb/b/06-b.jpg",
      "a": "assets-full/a/06-a.jpg",
      "aThumb": "assets-thumb/a/06-a.jpg",
      "online": "assets-full/online/06-online.jpg",
      "onlineThumb": "assets-thumb/online/06-online.jpg"
    },
    {
      "id": 7,
      "order": 7,
      "original": "assets-full/original/07-original.jpg",
      "originalThumb": "assets-thumb/original/07-original.jpg",
      "b": "assets-full/b/07-b.jpg",
      "bThumb": "assets-thumb/b/07-b.jpg",
      "a": "assets-full/a/07-a.jpg",
      "aThumb": "assets-thumb/a/07-a.jpg",
      "online": "assets-full/online/07-online.jpg",
      "onlineThumb": "assets-thumb/online/07-online.jpg"
    },
    {
      "id": 8,
      "order": 8,
      "original": "assets-full/original/08-original.jpg",
      "originalThumb": "assets-thumb/original/08-original.jpg",
      "b": "assets-full/b/08-b.jpg",
      "bThumb": "assets-thumb/b/08-b.jpg",
      "a": "assets-full/a/08-a.jpg",
      "aThumb": "assets-thumb/a/08-a.jpg",
      "online": "assets-full/online/08-online.jpg",
      "onlineThumb": "assets-thumb/online/08-online.jpg"
    },
    {
      "id": 9,
      "order": 9,
      "original": "assets-full/original/09-original.jpg",
      "originalThumb": "assets-thumb/original/09-original.jpg",
      "b": "assets-full/b/09-b.jpg",
      "bThumb": "assets-thumb/b/09-b.jpg",
      "a": "assets-full/a/09-a.jpg",
      "aThumb": "assets-thumb/a/09-a.jpg",
      "online": "assets-full/online/09-online.jpg",
      "onlineThumb": "assets-thumb/online/09-online.jpg"
    },
    {
      "id": 10,
      "order": 10,
      "original": "assets-full/original/10-original.jpg",
      "originalThumb": "assets-thumb/original/10-original.jpg",
      "b": "assets-full/b/10-b.jpg",
      "bThumb": "assets-thumb/b/10-b.jpg",
      "a": "assets-full/a/10-a.jpg",
      "aThumb": "assets-thumb/a/10-a.jpg",
      "online": "assets-full/online/10-online.jpg",
      "onlineThumb": "assets-thumb/online/10-online.jpg"
    },
    {
      "id": 11,
      "order": 11,
      "original": "assets-full/original/11-original.jpg",
      "originalThumb": "assets-thumb/original/11-original.jpg",
      "b": "assets-full/b/11-b.jpg",
      "bThumb": "assets-thumb/b/11-b.jpg",
      "a": "assets-full/a/11-a.jpg",
      "aThumb": "assets-thumb/a/11-a.jpg",
      "online": "assets-full/online/11-online.jpg",
      "onlineThumb": "assets-thumb/online/11-online.jpg"
    },
    {
      "id": 12,
      "order": 12,
      "original": "assets-full/original/12-original.jpg",
      "originalThumb": "assets-thumb/original/12-original.jpg",
      "b": "assets-full/b/12-b.jpg",
      "bThumb": "assets-thumb/b/12-b.jpg",
      "a": "assets-full/a/12-a.jpg",
      "aThumb": "assets-thumb/a/12-a.jpg",
      "online": "assets-full/online/12-online.jpg",
      "onlineThumb": "assets-thumb/online/12-online.jpg"
    },
    {
      "id": 13,
      "order": 13,
      "original": "assets-full/original/13-original.jpg",
      "originalThumb": "assets-thumb/original/13-original.jpg",
      "b": "assets-full/b/13-b.jpg",
      "bThumb": "assets-thumb/b/13-b.jpg",
      "a": "assets-full/a/13-a.jpg",
      "aThumb": "assets-thumb/a/13-a.jpg",
      "online": "assets-full/online/13-online.jpg",
      "onlineThumb": "assets-thumb/online/13-online.jpg"
    },
    {
      "id": 14,
      "order": 14,
      "original": "assets-full/original/14-original.jpg",
      "originalThumb": "assets-thumb/original/14-original.jpg",
      "b": "assets-full/b/14-b.jpg",
      "bThumb": "assets-thumb/b/14-b.jpg",
      "a": "assets-full/a/14-a.jpg",
      "aThumb": "assets-thumb/a/14-a.jpg",
      "online": "assets-full/online/14-online.jpg",
      "onlineThumb": "assets-thumb/online/14-online.jpg"
    },
    {
      "id": 15,
      "order": 15,
      "original": "assets-full/original/15-original.jpg",
      "originalThumb": "assets-thumb/original/15-original.jpg",
      "b": "assets-full/b/15-b.jpg",
      "bThumb": "assets-thumb/b/15-b.jpg",
      "a": "assets-full/a/15-a.jpg",
      "aThumb": "assets-thumb/a/15-a.jpg",
      "online": "assets-full/online/15-online.jpg",
      "onlineThumb": "assets-thumb/online/15-online.jpg"
    },
    {
      "id": 16,
      "order": 16,
      "original": "assets-full/original/16-original.jpg",
      "originalThumb": "assets-thumb/original/16-original.jpg",
      "b": "assets-full/b/16-b.jpg",
      "bThumb": "assets-thumb/b/16-b.jpg",
      "a": "assets-full/a/16-a.jpg",
      "aThumb": "assets-thumb/a/16-a.jpg",
      "online": "assets-full/online/16-online.jpg",
      "onlineThumb": "assets-thumb/online/16-online.jpg"
    },
    {
      "id": 17,
      "order": 17,
      "original": "assets-full/original/17-original.jpg",
      "originalThumb": "assets-thumb/original/17-original.jpg",
      "b": "assets-full/b/17-b.jpg",
      "bThumb": "assets-thumb/b/17-b.jpg",
      "a": "assets-full/a/17-a.jpg",
      "aThumb": "assets-thumb/a/17-a.jpg",
      "online": "assets-full/online/17-online.jpg",
      "onlineThumb": "assets-thumb/online/17-online.jpg"
    },
    {
      "id": 18,
      "order": 18,
      "original": "assets-full/original/18-original.jpg",
      "originalThumb": "assets-thumb/original/18-original.jpg",
      "b": "assets-full/b/18-b.jpg",
      "bThumb": "assets-thumb/b/18-b.jpg",
      "a": "assets-full/a/18-a.jpg",
      "aThumb": "assets-thumb/a/18-a.jpg",
      "online": "assets-full/online/18-online.jpg",
      "onlineThumb": "assets-thumb/online/18-online.jpg"
    }
  ]
};
